groups:
  - name: Webhook Alerts
    rules:
    - alert: HighWebhookErrorRate
      expr: rate(webhook_requests_total{status="error"}[5m]) > 0.1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: High webhook error rate
        description: "Error rate is {{ $value }} per second for the last 5 minutes"

    - alert: RabbitMQQueueBacklog
      expr: rabbitmq_queue_messages_ready > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: RabbitMQ queue has large backlog
        description: "Queue {{ $labels.queue }} has {{ $value }} messages waiting"

    - alert: MongoDBWriteErrors
      expr: mongodb_mongod_metrics_operation_total{type="writeErrors"} > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: MongoDB write errors detected
        description: "MongoDB is experiencing write errors"

    - alert: HighRetryCount
      expr: rate(webhook_retry_count_total[5m]) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High number of webhook retries
        description: "Webhooks are being retried at a rate of {{ $value }} per second"

    - alert: ProcessingDelay
      expr: histogram_quantile(0.95, rate(webhook_processing_duration_seconds_bucket[5m])) > 30
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Webhook processing is taking too long
        description: "95th percentile of webhook processing time is above 30 seconds"
